import {
  Type,
  Upload,
  Brush,
  Shapes,
  Camera,
  Mic,
  Video,
  Layers,
} from "lucide-react";

export type ToolOption = {
  id: string;
  title: string;
  icon: React.ComponentType<any>;
  description: string;
  content: string;
};

export const presetDimensions = [
  {
    label: "Instagram Post",
    value: "instagram-post",
    width: 1080,
    height: 1080,
  },
  {
    label: "Instagram Story",
    value: "instagram-story",
    width: 1080,
    height: 1920,
  },
  {
    label: "Facebook Post",
    value: "facebook-post",
    width: 1200,
    height: 630,
  },
  {
    label: "Facebook Cover",
    value: "facebook-cover",
    width: 1640,
    height: 859,
  },
  {
    label: "Twitter Post",
    value: "twitter-post",
    width: 1200,
    height: 675,
  },
  {
    label: "Twitter Header",
    value: "twitter-header",
    width: 1500,
    height: 500,
  },
  {
    label: "YouTube Thumbnail",
    value: "youtube-thumbnail",
    width: 1280,
    height: 720,
  },
  {
    label: "YouTube Banner",
    value: "youtube-banner",
    width: 2560,
    height: 1440,
  },
  {
    label: "LinkedIn Post",
    value: "linkedin-post",
    width: 1200,
    height: 627,
  },
  {
    label: "Pinterest Pin",
    value: "pinterest-pin",
    width: 1000,
    height: 1500,
  },
  {
    label: "A4 Document",
    value: "a4-document",
    width: 2480,
    height: 3508,
  },
  {
    label: "Business Card",
    value: "business-card",
    width: 1050,
    height: 600,
  },
  {
    label: "Custom",
    value: "custom",
    width: 0,
    height: 0,
  },
];

export const toolOptions: ToolOption[] = [
  {
    id: "text",
    title: "Text",
    icon: Type,
    description: "Add and edit text elements",
    content:
      "Create beautiful typography with our advanced text editor. Choose from hundreds of fonts, adjust spacing, and apply stunning effects to make your text stand out.",
  },
  {
    id: "upload",
    title: "Image Upload",
    icon: Upload,
    description: "Upload and manage images",
    content:
      "Drag and drop images or browse from your device. Supports JPG, PNG, SVG, and WebP formats. Automatic optimization and cloud storage included.",
  },
  {
    id: "draw",
    title: "Draw",
    icon: Brush,
    description: "Create custom drawings",
    content:
      "Use our powerful drawing tools to create custom artwork. Features include multiple brush types, layers, pressure sensitivity, and vector drawing capabilities.",
  },
  {
    id: "shapes",
    title: "Shapes",
    icon: Shapes,
    description: "Add geometric shapes",
    content:
      "Insert perfect circles, squares, triangles, and custom shapes. Easily modify colors, borders, and apply gradients to create stunning geometric designs.",
  },
  {
    id: "camera",
    title: "Camera",
    icon: Camera,
    description: "Capture photos directly",
    content:
      "Take photos directly from your device camera. Apply real-time filters, adjust lighting, and capture the perfect shot for your project.",
  },
  {
    id: "audio",
    title: "Audio",
    icon: Mic,
    description: "Record and edit audio",
    content:
      "Record high-quality audio, add background music, and apply audio effects. Support for multiple audio formats and professional editing tools.",
  },
  {
    id: "video",
    title: "Video",
    icon: Video,
    description: "Create and edit videos",
    content:
      "Import videos, trim clips, add transitions, and create professional-looking videos. Support for 4K resolution and various export formats.",
  },
  {
    id: "layers",
    title: "Layers",
    icon: Layers,
    description: "Manage content layers",
    content:
      "Organize your content with a powerful layer system. Group elements, adjust opacity, apply blend modes, and create complex compositions.",
  },
];

export const FONTS = [
  "ABeeZee",
  "Abel",
  "Abril Fatface",
  "Acme",
  "Alata",
  "Albert Sans",
  "Alegreya",
  "Alegreya Sans",
  "Alegreya Sans SC",
  "Alfa Slab One",
  "Alice",
  "Almarai",
  "Amatic SC",
  "Amiri",
  "Antic Slab",
  "Anton",
  "Architects Daughter",
  "Archivo",
  "Archivo Black",
  "Archivo Narrow",
  "Arimo",
  "Arsenal",
  "Arvo",
  "Asap",
  "Asap Condensed",
  "Assistant",
  "Barlow",
  "Barlow Condensed",
  "Barlow Semi Condensed",
  "Be Vietnam Pro",
  "Bebas Neue",
  "Bitter",
  "Black Ops One",
  "Bodoni Moda",
  "Bree Serif",
  "Bungee",
  "Cabin",
  "Cairo",
  "Cantarell",
  "Cardo",
  "Catamaran",
  "Caveat",
  "Chakra Petch",
  "Changa",
  "Chivo",
  "Cinzel",
  "Comfortaa",
  "Commissioner",
  "Concert One",
  "Cookie",
  "Cormorant",
  "Cormorant Garamond",
  "Courgette",
  "Crete Round",
  "Crimson Pro",
  "Crimson Text",
  "Cuprum",
  "DM Sans",
  "DM Serif Display",
  "DM Serif Text",
  "Dancing Script",
  "Didact Gothic",
  "Domine",
  "Dosis",
  "EB Garamond",
  "Eczar",
  "El Messiri",
  "Electrolize",
  "Encode Sans",
  "Encode Sans Condensed",
  "Exo",
  "Exo 2",
  "Figtree",
  "Fira Sans",
  "Fira Sans Condensed",
  "Fjalla One",
  "Francois One",
  "Frank Ruhl Libre",
  "Fraunces",
  "Gelasio",
  "Gloria Hallelujah",
  "Gothic A1",
  "Great Vibes",
  "Gruppo",
  "Heebo",
  "Hind",
  "Hind Madurai",
  "Hind Siliguri",
  "IBM Plex Mono",
  "IBM Plex Sans",
  "IBM Plex Sans Arabic",
  "IBM Plex Sans Condensed",
  "IBM Plex Serif",
  "Inconsolata",
  "Indie Flower",
  "Inter",
  "Inter Tight",
  "Josefin Sans",
  "Josefin Slab",
  "Jost",
  "Kalam",
  "Kanit",
  "Karla",
  "Kaushan Script",
  "Khand",
  "Lato",
  "League Spartan",
  "Lexend",
  "Lexend Deca",
  "Libre Barcode 39",
  "Libre Baskerville",
  "Libre Caslon Text",
  "Libre Franklin",
  "Lilita One",
  "Lobster",
  "Lobster Two",
  "Lora",
  "Luckiest Guy",
  "M PLUS 1p",
  "M PLUS Rounded 1c",
  "Macondo",
  "Manrope",
  "Marcellus",
  "Martel",
  "Mate",
  "Mate SC",
  "Maven Pro",
  "Merienda",
  "Merriweather",
  "Merriweather Sans",
  "Montserrat",
  "Montserrat Alternates",
  "Mukta",
  "Mulish",
  "Nanum Gothic",
  "Nanum Gothic Coding",
  "Nanum Myeongjo",
  "Neuton",
  "Noticia Text",
  "Noto Color Emoji",
  "Noto Kufi Arabic",
  "Noto Naskh Arabic",
  "Noto Sans",
  "Noto Sans Arabic",
  "Noto Sans Bengali",
  "Noto Sans Display",
  "Noto Sans HK",
  "Noto Sans JP",
  "Noto Sans KR",
  "Noto Sans Mono",
  "Noto Sans SC",
  "Noto Sans TC",
  "Noto Sans Thai",
  "Noto Serif",
  "Noto Serif JP",
  "Noto Serif KR",
  "Noto Serif TC",
  "Nunito",
  "Nunito Sans",
  "Old Standard TT",
  "Oleo Script",
  "Open Sans",
  "Orbitron",
  "Oswald",
  "Outfit",
  "Overpass",
  "Oxygen",
  "PT Sans",
  "PT Sans Caption",
  "PT Sans Narrow",
  "PT Serif",
  "Pacifico",
  "Passion One",
  "Pathway Gothic One",
  "Patua One",
  "Paytone One",
  "Permanent Marker",
  "Philosopher",
  "Play",
  "Playfair Display",
  "Plus Jakarta Sans",
  "Poppins",
  "Prata",
  "Prompt",
  "Public Sans",
  "Quattrocento",
  "Quattrocento Sans",
  "Questrial",
  "Quicksand",
  "Rajdhani",
  "Raleway",
  "Readex Pro",
  "Red Hat Display",
  "Righteous",
  "Roboto",
  "Roboto Condensed",
  "Roboto Flex",
  "Roboto Mono",
  "Roboto Serif",
  "Roboto Slab",
  "Rokkitt",
  "Rowdies",
  "Rubik",
  "Rubik Bubbles",
  "Rubik Mono One",
  "Russo One",
  "Sacramento",
  "Saira",
  "Saira Condensed",
  "Sarabun",
  "Satisfy",
  "Sawarabi Gothic",
  "Sawarabi Mincho",
  "Sen",
  "Shadows Into Light",
  "Signika",
  "Signika Negative",
  "Silkscreen",
  "Six Caps",
  "Slabo 27px",
  "Sora",
  "Source Code Pro",
  "Source Sans 3",
  "Source Serif 4",
  "Space Grotesk",
  "Space Mono",
  "Special Elite",
  "Spectral",
  "Tajawal",
  "Tangerine",
  "Teko",
  "Tinos",
  "Titan One",
  "Titillium Web",
  "Ubuntu",
  "Ubuntu Condensed",
  "Ubuntu Mono",
  "Unbounded",
  "Unna",
  "Urbanist",
  "Varela Round",
  "Vollkorn",
  "Work Sans",
  "Yanone Kaffeesatz",
  "Yantramanav",
  "Yellowtail",
  "Yeseva One",
  "Zen Kaku Gothic New",
  "Zeyada",
  "Zilla Slab",
];
